repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: Ruff linter
        args: ["check", "src", "tests"]
        types: [python]
        exclude: ^tests/manual/|\.ipynb$

      - id: ruff-format
        name: Ruff formatter
        args: ["format", "src", "tests"]
        types: [python]
        exclude: ^tests/manual/|\.ipynb$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: Mypy type checker
        args: ["--config-file=pyproject.toml"]
        types: [python]
        exclude: \.ipynb$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        name: Fix missing newline at EOF

      - id: trailing-whitespace
        name: Trim trailing whitespace
