[project]
name = "myproject"
dynamic = ["version"]
description = "A modern Python project template with optional CLI support."
authors = [
  {name = "Your Name", email = "your@email.com"}
]
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.9"

dependencies = []

[project.optional-dependencies]
dev = [
  "mypy",
  "ruff",
  "pytest",
  "coverage",
  "build",
  "twine",
  "pre-commit"
]

[project.scripts]
myproject = "myproject.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = { attr = "myproject.__version__" }
