[project]
name = "myproject"
dynamic = ["version"]
description = "A modern Python project template with optional CLI support."
authors = [
  {name = "Your Name", email = "your@email.com"}
]
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.9"

dependencies = [
  "colorama>=0.4.0"
]

[project.optional-dependencies]
dev = [
  "build",
  "coverage",
  "coverage==7.5.0",
  "coveralls>=3.3.2 ; python_version < '3.13'",
  "colorama",
  "mypy",
  "pre-commit",
  "pytest",
  "pytest-cov",
  "twine",
  "types-colorama",
  "ruff",
]

[project.scripts]
myproject = "myproject.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.mypy]
exclude = "\\.ipynb$"

[tool.ruff]
exclude = ["tests/manual/*"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = { attr = "myproject.__version__" }

# Pytest config
[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--maxfail=1 -v"
filterwarnings = [
  "ignore::pytest.PytestUnhandledThreadExceptionWarning"
]
